apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echo-server
spec:
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver
